### ISSUE TITLE
Pico C and Pro

### ISSUE THREAD

**Issue by olliephillips** [hotzenklotz/picobrew-server#1]
Very cool project - will this work on Pico C and Pro, the smaller units that are tied to the Pico Packs?

**Comment by hotzenklotz** [comment]
I only own the Zymatic and that’s all that I have ever used for testing. So, I don’t really know if it will work with any of the newer PicoBrew products. I would image that the most products use the same communication protocols but I can’t be sure.

If you end up getting a machine and get it to work with the server then please let me know so I can add it to the readme etc.

**Comment by olliephillips** [comment]
Thanks and will do. Out of interest how did you go about deducing the API. Wireshark or similar? Or looking at the firmware?

**Comment by hotzenklotz** [comment]
I used Wireshark. Their protocol was running on unencrypted HTTP at the time so relatively easy to decipher.
