### ISSUE TITLE
Exception on /API/logSession

### ISSUE THREAD

**Issue by danyou** [hotzenklotz/picobrew-server#14]
When starting brew session the following error is received:
picobrew_api.py", line 101, in create_new_session   recipe_file = recipe.filename
AttributeError: 'PicoBrewRecipe' object has no attribute 'filename'

[Zymatic error.txt](https://github.com/hotzenklotz/picobrew-server/files/4783354/Zymatic.error.txt)

[Party_Porter_recipe_xml.xml.txt](https://github.com/hotzenklotz/picobrew-server/files/4783361/Party_Porter_recipe_xml.xml.txt)

**Comment by danyou** [comment]
Also after installing with  pip install picobrew_server, I noted the following difference in frontend.py line 47:
 logger.error(f"Failed to parse recipe {filename}. {error}")

and not the following, updated previously:
logger.error("Failed to parse recipe %s. %s", filename, error)

**Comment by hotzenklotz** [comment]
Thanks for reporting this issue. I fixed it. Should be published as PicoBrew Server `v1.0.1`.

**Comment by danyou** [comment]
Thank you for the update.  I can step through the brew cycle now.  Not sure if this matters but there is an error at the end when exiting the session.

picobrew_api.py", line 128, in log_to_session   data = args["data"]   KeyError: 'data'

[455deab29fa14c6896e8b572db5b93aa.json.txt](https://github.com/hotzenklotz/picobrew-server/files/4787995/455deab29fa14c6896e8b572db5b93aa.json.txt)
[Not_Yet-ie_recipe_xml.xml.txt](https://github.com/hotzenklotz/picobrew-server/files/4788002/Not_Yet-ie_recipe_xml.xml.txt)
[error.txt](https://github.com/hotzenklotz/picobrew-server/files/4788006/error.txt)
